### ISSUE TITLE
Conflicts after Branch Merged with Master

### ISSUE THREAD

**Issue by Reyna-5970** [Agile-and-Adaptive-Robotics/Inverted_Pendulum#5] opened 2020-06-22 22:42 UTC
I'm not completely sure how it happened but after my last pull request (#4) was approved & merged, when I went to commit files to a new branch, there were conflicts in the files. I did fetch from origin (a couple times) before creating a new branch from master. When I reopened the files after merging, they seemingly returned to the state before I merged #4 with master, so I closed Solidworks and restarted the program. My files appeared as they should be (so that master was up-to-date with the latest version), but now I wonder if this resulted in file conflicts. I tried to commit anyway and might have created more problems in doing so...

**Comment by jakechung42** [comment] 2020-06-22 22:49
I will look into this.

**Comment by jakechung42** [comment] 2020-06-22 22:52
@Reyna-5970 this conflict occurs on tendonsAndSlots-ReynaAy-feat branch? When you created this branch, did you create this branch from master?

**Comment by Reyna-5970** [comment] 2020-06-22 22:56
@jakechung42 I know that tendonsAndSlots-ReynaAy-feat as well as bpaMount-ReynaAy-feat were both created from master. If I just deleted bpaMount-ReynaAy-feat and then created a new branch from the most up-to-date master, should this resolve the issue?

**Comment by jakechung42** [comment] 2020-06-22 22:59
You can try that, but you don't need to delete the old branches until you are sure that the issue is resolved.

**Comment by jakechung42** [comment] 2020-06-22 23:00
However, the tendonsAndSlots-ReynaAy-feat branch is merged. It can be deleted.

**Comment by jakechung42** [comment] 2020-06-22 23:00
I don't see the bpaMount-ReynaAy-feat branch. Have you published it?

**Comment by jakechung42** [comment] 2020-06-22 23:05
I see the bpaMount-ReynaAy-feat now. The commit history of that branch is very wacky. It doesn't seem to have been created from the master branch. Can you make another branch of off master and copy to that branch your progress? (You might want to copy the files to a temporary location since when you switch branch, the content of that branch will also change)

**Comment by Reyna-5970** [comment] 2020-06-22 23:09
I am trying to switch my current branch to master but it just shows the error message: `you need to resolve your current index first`

**Comment by jakechung42** [comment] 2020-06-22 23:10
let's hope on Zoom. https://pdx.zoom.us/j/96739091812

**Comment by jakechung42** [comment] 2020-06-22 23:19
Issue is resolved. The seems like the bpaMount-ReynaAy-feat branch was created when the master branch doesn't have all the updated features, so it created conflicts when Reyna tried to push.

**Closed by jakechung42** 2020-06-22 23:19 UTC
Labels: good first issue, help wanted
